[package]
name = "wm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]

[dependencies]
xcb = { version = "1.2.0", features = ["randr"] }
x11rb = { version = "0.11.0", features = ["randr"] }
